version: '2'

volumes:
  settings:

services:
  kiosk:
    depends_on:
        - noisy
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 5011:5011
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  browsercontrol:
    build: ./browsercontrol
    restart: always
    privileged: true
    ports:
      - 8080:80
  pulse:
    # https://github.com/balenablocks/pulse
    image: balenablocks/pulse
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      # GPIO_PIN: 4 # add to balenaCloud Device Variables
      # PULL_UP_DOWN: down # add to balenaCloud Device Variables
      ALWAYS_USE_HTTPSERVER: True
    expose:
      - 7575
  noisy:
    depends_on:
        - pulse
    build: ./noisy
    restart: always
    ports:
      - 80:80
      - 8585:8585
